version: 1.0.0.{build}-{branch}

configuration:
  - Debug 
  - Release

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - /develop/
  - /master/

skip_tags: true

build_script:
- ps: .\build.ps1

test: off